<div class="row">
	<div class="columns twelve">
		<!-- The following was generated by http://snapwidget.com/#getstarted -->
		<iframe src="http://snapwidget.com/sl/?u=Y2FydG9ncmFtfGlufDEwMHwyfDN8fHllc3w1fG5vbmU=" allowTransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden; width:115px; height: 115px" ></iframe>
	</div>
</div>
<div class="row">
	<div class="columns seven">
		<div class="row">
			<div class="columns twelve">
				Highlight Reel
			</div>
		</div>
		<div class="row">
			<div class="columns twelve">
				<?php
				global $myExcerptLength;
				$myExcerptLength = 20;
				$query = new WP_Query('showposts=1');
				while ($query->have_posts()): $query->the_post();
					echo get_the_date('jS F, Y');
					the_excerpt();
				endwhile;
				$myExcerptLength = 0;
				?>
			</div>
		</div>
	</div>
	<div class="columns five">
		<div class="row">
			<div class="columns twelve">
				MVP
			</div>
		</div>
		<div class="row">
			<?php 
				$foundMVP = false;
				$beers = new WP_Query(array("post_type" => "beers"));
				while ($beers->have_posts() && !$foundMVP): $beers->the_post();
					if (get_post_meta( $post->ID, '_cartogram_mvp_value', TRUE )) {
						$foundMVP = true;
						$image = wp_get_attachment_image_src( get_post_thumbnail_id( $post->ID ), 'single-post-thumbnail' );
						$permalink = get_permalink( $post->ID );
					}
				endwhile;
				?>
			<div class="columns twelve mvp" style="background-image: url('<?php echo $image[0]; ?>')">
				<?php the_title(); ?>
				<a href="<?php echo $permalink; ?>">Learn More</a>
			</div>
		</div>
	</div>
</div>
