on: 
  push:
    branches:
      - master
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@v4.0.0
      with:
        ftp-server: ftp.leftfieldbrewery.ca
        ftp-username: cartogram@leftfieldbrewery.ca
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        exclude: |
        - wp-content/uploads/**
        - wp-admin/**/
        - .htaccess
