on: 
  push:
    branches:
      - master
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftp.leftfieldbrewery.ca
        username: cartogram@leftfieldbrewery.ca
        password: ${{ secrets.FTP_PASSWORD }}
        exclude: |
        wp-content/plugins/
        wp-content/uploads/
        wp-content/wp-includes/
        wp-content/wpflogs/
        wp-admin
        .htaccess
